#!/bin/bash

LABELS="$LABELS VU_LINUX_PKGS_OPENSOURCE_KERNEL"
LABELS="$LABELS VU_LINUX_PKGS_OPENSOURCE_MODULE_INIT_TOOLS"
LABELS="$LABELS VU_LINUX_PKGS_OPENSOURCE_MTD_UTILS"
LABELS="$LABELS VU_LINUX_PKGS_OPENSOURCE_YAFFS2"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_BOOTWEDGE"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_BT"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_DATA"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_ELFED"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_GPS"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_KERNEL_TESTS"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_LIBRPC"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_MKNANDIMAGE"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_MM_ADSPSVC"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_MM_OMXH264DEC"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_MM_OMXCORE"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_MM_OMXVENC"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_MODEM_API"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_ONCRPC"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_QCOM_COMMON"
LABELS="$LABELS VU_LINUX_PKGS_PROPRIETARY_STRINGL"
LABELS="$LABELS VU_LINUX_TARGET_COMMON"
LABELS="$LABELS VU_LINUX_TARGET_MSM7201A"
LABELS="$LABELS VU_LINUX_TARGET_MSM7625"
LABELS="$LABELS VU_LINUX_TARGET_QSD8650"
LABELS="$LABELS VU_LINUX_TARGET_QST1105"

for i in $( echo $LABELS ); do
  echo "Creating label $i.$2 from $i.$1..."
  p4 label -o -t $i.$1 $i.$2 |  sed 's/Options.*locked/Options:        unlocked/g' | p4 label -i

  echo "Syncing label $i.$2 to workspace..."
  p4 labelsync -l $i.$2
done
