#!/usr/local/bin/perl

use strict;

my $debug = 1;

sub execute_getvu_line($)
{
  my $res = "";
  my $cmd = "";
  my $plf = 0;

  if (/^@([\w.]+)/)
  {
    # It's a label
    $cmd = "p4 sync @" . "$1,$1";
  }
  elsif (/^(\/\/.*)/)
  {
    # It's a file
    $cmd = "p4 sync $1";
  }
  elsif (/^PLF=(.*)$/)
  {
    # It's a PLF
    $plf = 1;
    $cmd = "p4 sync -f $1";
  }

  if ($cmd ne "")
  {
    print "$cmd\n";

    $res = `$cmd 2>&1`;
    if (($res =~ /^Invalid changelist/) ||
        ($res =~ /not in client view/))
    {
      print "ERROR in changelist!!!\n";
      print "$res\n";
      #die $res;
    }
    else
    {
      print $res;
    }
  }

  if ($plf)
  {
    if ($res =~ /(refreshing|added as) (.*)$/)
    {
      my $fd;
      open $fd, $2;
      while (<$fd>)
      {
        &execute_getvu_line($_);
      }
      close $fd;
    }
    else
    {
      print "ERROR - not refreshing label!!!\n";
      die "$1 does not exist\n";
    }
  }
}

while (<>)
{
  &execute_getvu_line($_);
}
