#!/bin/bash 

p4 sync -f @VU_PLATFORM_LINUX_BOOT.$1,@VU_PLATFORM_LINUX_BOOT.$1 &
p4 sync -f @VU_PLATFORM_LINUX_BUILD_INTERNAL.$1,@VU_PLATFORM_LINUX_BUILD_INTERNAL.$1 &
p4 sync -f @VU_PLATFORM_LINUX_COMMON.$1,@VU_PLATFORM_LINUX_COMMON.$1 &
p4 sync -f @VU_PLATFORM_LINUX_MODULES.$1,@VU_PLATFORM_LINUX_MODULES.$1 &
p4 sync -f @VU_PLATFORM_LINUX_ROOTFS_INTERNAL.$1,@VU_PLATFORM_LINUX_ROOTFS_INTERNAL.$1 &
p4 sync -f @VU_PLATFORM_LINUX_TESTS.$1,@VU_PLATFORM_LINUX_TESTS.$1 &
p4 sync -f @VU_PLATFORM_LINUX_KERNEL_INTERNAL.$1,@VU_PLATFORM_LINUX_KERNEL_INTERNAL.$1 &

